# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d7d4bd3ba1c5a5ffdc45fc35c822ce9"
name = "store-product-app"
handle = "store-product-app"
application_url = "https://car-fired-persian-ali.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appproduct.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://car-fired-persian-ali.trycloudflare.com/auth/callback",
  "https://car-fired-persian-ali.trycloudflare.com/auth/shopify/callback",
  "https://car-fired-persian-ali.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
